// Fetch Google Fonts CSS, download latin + latin-ext woff2 files, rewrite to
// local /fonts/ URLs, write public/assets/css/fonts.css.
//
// Run when the font request changes (rare). Output is checked in.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FONTS_URL =
  'https://fonts.googleapis.com/css2?' +
  'family=Cormorant+Garamond:ital,wght@0,300;0,400;0,600;1,300;1,400;1,600' +
  '&family=Outfit:wght@300;400;500' +
  '&display=swap';

const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) ' +
  'Chrome/120.0.0.0 Safari/537.36';

const OUT_FONTS = path.join(__dirname, 'public', 'fonts');
const OUT_CRITICAL = path.join(__dirname, 'public', 'assets', 'css', 'fonts-critical.css');
const OUT_DEFERRED = path.join(__dirname, 'public', 'assets', 'css', 'fonts-deferred.css');

const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

// Weights used above-the-fold on the home page (hero h1, nav logo, body default,
// btn-gold). All others are below-fold (menu items, marquee, blog cards, etc.)
// and load with deferred CSS so they don't fight for the critical-path budget.
const CRITICAL = new Set([
  'Cormorant Garamond|normal|300',
  'Cormorant Garamond|italic|300',
  'Cormorant Garamond|normal|600',
  'Outfit|normal|400',
  'Outfit|normal|500',
]);

fs.mkdirSync(OUT_FONTS, { recursive: true });

const cssRes = await fetch(FONTS_URL, { headers: { 'User-Agent': UA } });
const css = await cssRes.text();

// Each block looks like:
// /* SUBSET */
// @font-face {
//   font-family: 'X';
//   font-style: Y;
//   font-weight: Z;
//   font-display: swap;
//   src: url(https://fonts.gstatic.com/...woff2) format('woff2');
//   unicode-range: ...;
// }
const blockRe = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;

const blocks = [];
let m;
while ((m = blockRe.exec(css))) {
  const subset = m[1];
  const body = m[2];
  if (!KEEP_SUBSETS.has(subset)) continue;
  const fontFamily = /font-family:\s*'([^']+)'/.exec(body)?.[1];
  const fontStyle = /font-style:\s*(\w+)/.exec(body)?.[1] ?? 'normal';
  const fontWeight = /font-weight:\s*(\d+)/.exec(body)?.[1] ?? '400';
  const srcUrl = /src:\s*url\((https:[^)]+)\)/.exec(body)?.[1];
  const unicodeRange = /unicode-range:\s*([^;]+)/.exec(body)?.[1];
  if (!srcUrl) continue;
  blocks.push({ subset, fontFamily, fontStyle, fontWeight, srcUrl, unicodeRange });
}

console.log(`Found ${blocks.length} @font-face blocks to keep (latin/latin-ext)`);

let totalBytes = 0;
const critical = [];
const deferred = [];
for (const b of blocks) {
  const slug =
    b.fontFamily.toLowerCase().replace(/\s+/g, '-') +
    `-${b.fontStyle}-${b.fontWeight}-${b.subset}.woff2`;
  const localPath = path.join(OUT_FONTS, slug);
  if (!fs.existsSync(localPath)) {
    const r = await fetch(b.srcUrl);
    const buf = Buffer.from(await r.arrayBuffer());
    fs.writeFileSync(localPath, buf);
    console.log(`  ↓ ${slug} (${(buf.length / 1024).toFixed(1)} KB)`);
    totalBytes += buf.length;
  } else {
    totalBytes += fs.statSync(localPath).size;
  }
  const block = `@font-face {
  font-family: '${b.fontFamily}';
  font-style: ${b.fontStyle};
  font-weight: ${b.fontWeight};
  font-display: swap;
  src: url('/fonts/${slug}') format('woff2');
  unicode-range: ${b.unicodeRange};
}`;
  const key = `${b.fontFamily}|${b.fontStyle}|${b.fontWeight}`;
  if (CRITICAL.has(key)) critical.push(block);
  else deferred.push(block);
}

const header = '/* Auto-generated by fetch-fonts.mjs — do not hand-edit. */\n';
fs.writeFileSync(OUT_CRITICAL, header + critical.join('\n') + '\n');
fs.writeFileSync(OUT_DEFERRED, header + deferred.join('\n') + '\n');

console.log(
  `\n✓ Critical fonts CSS: ${OUT_CRITICAL} (${(fs.statSync(OUT_CRITICAL).size / 1024).toFixed(1)} KB, ${critical.length} blocks)`,
);
console.log(
  `✓ Deferred fonts CSS: ${OUT_DEFERRED} (${(fs.statSync(OUT_DEFERRED).size / 1024).toFixed(1)} KB, ${deferred.length} blocks)`,
);
console.log(`✓ Total woff2 bytes: ${(totalBytes / 1024).toFixed(1)} KB across ${blocks.length} files`);
